const { admin, db } = require('../config/firebaseAdmin');

const sampleUsers = [
  {
    uid: "test_user_1", // This is a placeholder, usually real UIDs are generated by Auth
    email: "john.doe@example.com",
    prenom: "John",
    nom: "Doe",
    role: "user",
    status: "active",
    joinedAt: admin.firestore.FieldValue.serverTimestamp()
  },
  {
    uid: "test_user_2",
    email: "jane.smith@example.com",
    prenom: "Jane",
    nom: "Smith",
    role: "user",
    status: "blocked",
    joinedAt: admin.firestore.FieldValue.serverTimestamp()
  }
];

async function seedUsers() {
  try {
    const usersRef = db.collection('users');
    const batch = db.batch();

    for (const user of sampleUsers) {
      // NOTE: In a real scenario, you would create the Auth user first to get a real UID.
      // For this seed script, we just populate Firestore for UI testing.
      const docRef = usersRef.doc(user.uid);
      batch.set(docRef, user);
    }

    await batch.commit();
    console.log('Utilisateurs de test ajoutés à Firestore avec succès !');
    console.log('Note: Ces UIDs sont fictifs et ne correspondent pas à des comptes Auth réels.');
    process.exit(0);
  } catch (error) {
    console.error('Erreur lors de l\'ajout des utilisateurs de test:', error);
    process.exit(1);
  }
}

seedUsers();
